variables: 
 - template: config.yml

trigger: none

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: AzureCLI@2
  displayName: 'Install AML CLI'
  inputs:
    azureSubscription: $(ml-ws-connection)
    scriptLocation: inlineScript
    scriptType: bash
    inlineScript: |
      az extension add -n azure-cli-ml

- task: AzureCLI@2
  displayName: 'Attach folder to workspace'
  inputs:
    azureSubscription: $(ml-ws-connection)
    workingDirectory: $(ml-path)
    scriptLocation: inlineScript
    scriptType: bash
    inlineScript: |
      az ml folder attach -w $(ml-ws) -g $(ml-rg)

- task: AzureCLI@2
  displayName: 'Deploy model to AKS for Production'
  inputs:
    azureSubscription: $(ml-ws-connection)
    workingDirectory: $(ml-path)
    scriptLocation: inlineScript
    scriptType: bash
    inlineScript: |
      LATEST_VERSION=`az ml model list -n $(ml-model-name) --query '[0].version'`
      az ml model deploy -n ibm-attrition-aks --ct $(ml-aks-name) -m $(ml-model-name):$LATEST_VERSION --ic deployment-config/inference-config.yml --dc deployment-config/deployment-config-aks.yml  --overwrite