variables: 
 - template: config.yml

trigger: none

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: AzureCLI@2
  displayName: 'Install AML CLI'
  inputs:
    azureSubscription: $(ml-ws-connection)
    scriptLocation: inlineScript
    scriptType: bash
    inlineScript: |
      az extension add -n azure-cli-ml

- task: AzureCLI@2
  displayName: 'Attach folder to workspace'
  inputs:
    azureSubscription: $(ml-ws-connection)
    workingDirectory: $(ml-path)
    scriptLocation: inlineScript
    scriptType: bash
    inlineScript: |
      az ml folder attach -w $(ml-ws) -g $(ml-rg)

- task: AzureCLI@2
  displayName: 'Delete training cluster'
  inputs:
    azureSubscription: $(ml-ws-connection)
    workingDirectory: $(ml-path)
    scriptLocation: inlineScript
    scriptType: bash
    inlineScript: |
      az ml computetarget delete -n $(ml-ct)

- task: AzureCLI@2
  displayName: 'Delete AKS cluster'
  inputs:
    azureSubscription: $(ml-ws-connection)
    workingDirectory: $(ml-path)
    scriptLocation: inlineScript
    scriptType: bash
    inlineScript: |
      az ml computetarget delete -n $(ml-aks-name)