
variables: 
 - template: config.yml

trigger: none

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: AzureCLI@2
  displayName: 'Install AML CLI'
  inputs:
    azureSubscription: $(ml-ws-connection)
    scriptLocation: inlineScript
    scriptType: bash
    inlineScript: |
      az extension add -n azure-cli-ml

- task: AzureCLI@2
  displayName: 'Attach folder to workspace'
  inputs:
    azureSubscription: $(ml-ws-connection)
    workingDirectory: $(ml-path)
    scriptLocation: inlineScript
    scriptType: bash
    inlineScript: |
      az ml folder attach -w $(ml-ws) -g $(ml-rg)
  
- task: AzureCLI@2
  displayName: 'Train model'
  inputs:
    azureSubscription: $(ml-ws-connection)
    workingDirectory: $(ml-path)
    scriptLocation: inlineScript
    scriptType: bash
    inlineScript: |
      az ml run submit-script -c train --ct $(ml-ct) -e $(ml-exp) -t run.json train_explain.py

# Add potential approval step before registration of model

- task: AzureCLI@2
  displayName: 'Register model'
  inputs:
    azureSubscription: $(ml-ws-connection)
    workingDirectory: $(ml-path)
    scriptLocation: inlineScript
    scriptType: bash
    inlineScript: |
      az ml model register -n $(ml-model-name) -f run.json --asset-path outputs/original_model.pkl -t model.json


# - task: AzureCLI@2
#   displayName: 'Create ML pipeline'
#   inputs:
#     azureSubscription: $(ml-ws-connection)
#     workingDirectory: $(ml-path)
#     scriptLocation: inlineScript
#     scriptType: bash
#     inlineScript: |
#       az ml pipeline create --name trainattrition -y training-ml-pipeline.yml